GET http://localhost:8000/get HTTP/1.1

###

POST http://localhost:8000/post HTTP/1.1
Content-Type: application/json

{
    "name":"Gabor",
    "firstname":"Aron"
}

###
POST http://localhost:8000/auth/login
Content-Type: application/json

{
    "username" : "Anyname"
}

####
GET http://localhost:8000/auth/test
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQW55bmFtZSIsImlhdCI6MTY1MzY3Mjc4M30.q0upwlyPP-tXN9oe0bluwQm4yqLzY08v5NaioRQTjDs
Content-Type: application/json

{
    "asd" : "asfdsa"
}
###
POST http://localhost:8000/auth/register
Content-Type: application/json

{
    "name" : "Name",
    "email" : "Email",
    "pass" : "Password"
}
###
GET http://localhost:8000/auth/allUser
###
POST http://localhost:8000/auth/login
Content-Type: application/json

{
    "name" : "Name",
    "email" : "Email",
    "pass" : "Password"
}
###
POST http://localhost:8000/profile/updateProfile
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.RW1haWw.Sf2rM3Xp4nqy5oFJbD1taTjAxtml7MQXH-CYaGCEDho

###

POST http://localhost:8000/stuffs/addStuff
Content-Type: application/json

{
    "title": "title",
    "author": "author",
    "genre": "genre",
    "type": "type",
    "describe": "describe",
    "img": "imglink",
    "links": "linksssss"
}

###
POST http://localhost:8000/posts/addPost
Content-Type: application/json

{
    "title": "sometitle",
    "user": "gooduser",
    "content": "goodcontent"
}
###
POST http://localhost:8000/posts/addComment
Content-Type: application/json

{
    "id":"62a354bba4facd6935d5207f",
    "user": "gooduser",
    "content": "Goodcontent"
}
###
GET http://localhost:8000/posts/post
